name: build-paper

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: cv # exclude the '.tex' / '.pdf' extension!
      LATEX: pdflatex -shell-escape
    steps:
      - uses: actions/checkout@v1
      - name: Install texlive
        run: |
          sudo apt-get update
          sudo apt-get install texlive-publishers \
                               texlive-latex-recommended \
                               texlive-latex-extra \
                               texlive-fonts-recommended \
                               texlive-fonts-extra
      - name: Build paper
        run: |
          export ENV=GIT
          ${LATEX} ${MANUSCRIPT_PATH}.tex
          ${LATEX} ${MANUSCRIPT_PATH}.tex
      - name: Push paper
        run: |
          git checkout --orphan ${GITHUB_REF##*/}-pdf
          git rm -rf .github/
          git rm -rf . 
          git add -f ${MANUSCRIPT_PATH}.pdf
          git -c user.name='build-pdf' -c user.email='build-pdf' commit -m "Update PDF"
          git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
